name: Release

on:
  push:
    tags: ["*.*.*"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login
        run: cargo login --verbose ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish
        run: cargo publish --verbose

      - name: GitHub release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
