name: Release

on:
  push:
    tags: ["*.*.*"]
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: cargo login --verbose ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish
        run: cargo publish --verbose

      - name: GitHub
        run: gh release create ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
